name: Test (presets)

on:
  pull_request:
    branches: [ presets ]
  workflow_call:
    inputs:
      ref:
        type: string
      repo:
        type: string

permissions:
  contents: read

jobs:
  test:
    name: Test checked-out presets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - name: Setup metrics
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm run test-presets
        env:
          HEAD_REF: ${{ inputs.ref || github.head_ref || 'presets' }}
          REPO: ${{ inputs.repo || github.event.pull_request.head.repo.full_name || github.repository }}